require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('./models/Product');

const seedProductsData = [
  // Women Western
  {
    name: 'Women’s T-Shirt',
    brand: 'Tokyo',
    price: 650,
    size: 'M',
    group: 'Women',
    category: 'Women',
    style: 'Western',
    type: 'Tops',
    material: 'Cotton',
    condition: 'Good',
    imageUrl: '/src/assets/products/womantshirt.jpg',
    image: '/src/assets/products/womantshirt.jpg',
  },
  {
    name: 'Cotton Shirt',
    brand: 'Aarong',
    price: 850,
    size: 'S',
    group: 'Women',
    category: 'Women',
    style: 'Western',
    type: 'Tops',
    material: 'Soft cotton',
    condition: 'Good',
    imageUrl: '/src/assets/products/womantop.jpg',
    image: '/src/assets/products/womantop.jpg',
  },
  {
    name: 'Women’s Jeans',
    brand: "Levi's",
    price: 1200,
    size: '28',
    group: 'Women',
    category: 'Women',
    style: 'Western',
    type: 'Tops',
    material: 'Denim',
    condition: 'Good',
    imageUrl: '/src/assets/products/womanjeans.jpg',
    image: '/src/assets/products/womanjeans.jpg',
  },
  {
    name: 'Women’s Scarf',
    brand: 'Deshal',
    price: 750,
    size: 'Free size',
    group: 'Women',
    category: 'Women',
    style: 'Western',
    type: 'Scarf',
    material: 'Cotton voile',
    condition: 'Like New',
    imageUrl: '/src/assets/products/womenscaff.jpg',
    image: '/src/assets/products/womenscaff.jpg',
  },
  {
    name: 'Floral Frock',
    brand: 'Forever 21',
    price: 1350,
    size: 'S',
    group: 'Women',
    category: 'Women',
    style: 'Western',
    type: 'Tops',
    material: 'Georgette',
    condition: 'Like New',
    imageUrl:
      'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=1200&q=90',
    image:
      'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=1200&q=90',
  },
  {
    name: 'Denim Jumpsuit',
    brand: 'Bershka',
    price: 1450,
    size: 'M',
    group: 'Women',
    category: 'Women',
    style: 'Western',
    type: 'Tops',
    material: 'Denim blend',
    condition: 'Like New',
    imageUrl:
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=90',
    image:
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=90',
  },

  // Sarees
  {
    name: 'Rose Gold Katan Saree',
    brand: 'Katan',
    price: 1200,
    size: 'Free size',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Saree',
    material: 'Katan silk',
    usedFor: 'Used for 2 months',
    condition: 'Like New',
    imageUrl: '/src/assets/products/sarees/katan-4.jpg',
    image: '/src/assets/products/sarees/katan-4.jpg',
  },
  {
    name: 'Black & Red Katan Saree',
    brand: 'Katan',
    price: 1150,
    size: 'Free size',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Saree',
    material: 'Katan silk',
    usedFor: 'Used for 4 months',
    condition: 'Like New',
    imageUrl: '/src/assets/products/sarees/katan-3.jpg',
    image: '/src/assets/products/sarees/katan-3.jpg',
  },
  {
    name: 'Fuchsia Floral Katan Saree',
    brand: 'Katan',
    price: 1200,
    size: 'Free size',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Saree',
    material: 'Katan silk',
    usedFor: 'Used for 1 month',
    condition: 'Like New',
    imageUrl: '/src/assets/products/sarees/katan-5.jpg',
    image: '/src/assets/products/sarees/katan-5.jpg',
  },
  {
    name: 'Emerald Green Katan Saree',
    brand: 'Katan',
    price: 1100,
    size: 'Free size',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Saree',
    material: 'Katan silk',
    usedFor: 'Used for 3 months',
    condition: 'Good',
    imageUrl: '/src/assets/products/sarees/katan-green.jpg',
    image: '/src/assets/products/sarees/katan-green.jpg',
  },
  {
    name: 'Wine Red Katan Saree',
    brand: 'Katan',
    price: 1200,
    size: 'Free size',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Saree',
    material: 'Katan silk',
    usedFor: 'Used for 2 months',
    condition: 'Like New',
    imageUrl: '/src/assets/products/sarees/katan-maroon.jpg',
    image: '/src/assets/products/sarees/katan-maroon.jpg',
  },
  {
    name: 'Black Monipuri Saree',
    brand: 'Monipuri',
    price: 850,
    size: 'Free size',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Saree',
    material: 'Monipuri cotton',
    usedFor: 'Used for 5 months',
    condition: 'Good',
    imageUrl: '/src/assets/products/sarees/monipuri-black.jpg',
    image: '/src/assets/products/sarees/monipuri-black.jpg',
  },
  {
    name: 'Lavender Monipuri Saree',
    brand: 'Monipuri',
    price: 800,
    size: 'Free size',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Saree',
    material: 'Monipuri cotton',
    usedFor: 'Used for 2 months',
    condition: 'Like New',
    imageUrl: '/src/assets/products/sarees/monipuri-purple.jpg',
    image: '/src/assets/products/sarees/monipuri-purple.jpg',
  },
  {
    name: 'Blue & White Monipuri Saree',
    brand: 'Monipuri',
    price: 900,
    size: 'Free size',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Saree',
    material: 'Monipuri cotton',
    usedFor: 'Used for 4 months',
    condition: 'Good',
    imageUrl: '/src/assets/products/sarees/monipuri-blue.jpg',
    image: '/src/assets/products/sarees/monipuri-blue.jpg',
  },
  {
    name: 'Sunshine Yellow Monipuri Saree',
    brand: 'Monipuri',
    price: 950,
    size: 'Free size',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Saree',
    material: 'Monipuri cotton',
    usedFor: 'Used for 1 month',
    condition: 'Like New',
    imageUrl: '/src/assets/products/sarees/monipuri-yellow.jpg',
    image: '/src/assets/products/sarees/monipuri-yellow.jpg',
  },
  {
    name: 'Yellow Border Monipuri Saree',
    brand: 'Monipuri',
    price: 750,
    size: 'Free size',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Saree',
    material: 'Monipuri cotton',
    usedFor: 'Used for 6 months',
    condition: 'Good',
    imageUrl: '/src/assets/products/sarees/monipuri-yellow-border.jpg',
    image: '/src/assets/products/sarees/monipuri-yellow-border.jpg',
  },
  {
    name: 'Purple Embellished Cotton Saree',
    brand: 'Cotton',
    price: 1050,
    size: 'Free size',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Saree',
    material: 'Soft cotton',
    usedFor: 'Used for 2 months',
    condition: 'Like New',
    imageUrl: '/src/assets/products/sarees/cotton-purple.jpg',
    image: '/src/assets/products/sarees/cotton-purple.jpg',
  },
  {
    name: 'Mauve Cotton Saree',
    brand: 'Cotton',
    price: 700,
    size: 'Free size',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Saree',
    material: 'Pure cotton',
    usedFor: 'Used for 5 months',
    condition: 'Good',
    imageUrl: '/src/assets/products/sarees/cotton-mauve.jpg',
    image: '/src/assets/products/sarees/cotton-mauve.jpg',
  },
  {
    name: 'Olive Green Cotton Saree',
    brand: 'Cotton',
    price: 850,
    size: 'Free size',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Saree',
    material: 'Pure cotton',
    usedFor: 'Used for 3 months',
    condition: 'Like New',
    imageUrl: '/src/assets/products/sarees/cotton-green.jpg',
    image: '/src/assets/products/sarees/cotton-green.jpg',
  },
  {
    name: 'Olive Cotton Silk Saree',
    brand: 'Cotton Silk',
    price: 1100,
    size: 'Free size',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Saree',
    material: 'Cotton silk blend',
    usedFor: 'Used for 2 months',
    condition: 'Like New',
    imageUrl: '/src/assets/products/sarees/cotton-silk-olive.jpg',
    image: '/src/assets/products/sarees/cotton-silk-olive.jpg',
  },

  // Salwar Kameez
  {
    name: 'Maroon Embroidered Salwar Kameez',
    brand: 'Aarong',
    price: 600,
    size: 'M',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Salwar Kameez',
    material: 'Embroidered cotton',
    usedFor: 'Used for 2 months',
    condition: 'Like New',
    imageUrl: '/src/assets/products/salwar-kameez/maroon-embroidered.jpg',
    image: '/src/assets/products/salwar-kameez/maroon-embroidered.jpg',
  },
  {
    name: 'Blush Formal Salwar Kameez',
    brand: 'Kay Kraft',
    price: 550,
    size: 'M',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Salwar Kameez',
    material: 'Embroidered georgette',
    usedFor: 'Used for 3 months',
    condition: 'Like New',
    imageUrl: '/src/assets/products/salwar-kameez/blush-formal.jpg',
    image: '/src/assets/products/salwar-kameez/blush-formal.jpg',
  },
  {
    name: 'Sky Blue Classic Salwar Kameez',
    brand: 'Deshal',
    price: 450,
    size: 'L',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Salwar Kameez',
    material: 'Soft cotton',
    usedFor: 'Used for 4 months',
    condition: 'Good',
    imageUrl: '/src/assets/products/salwar-kameez/sky-blue-classic.jpg',
    image: '/src/assets/products/salwar-kameez/sky-blue-classic.jpg',
  },
  {
    name: 'Olive Floral Salwar Kameez',
    brand: 'Aarong',
    price: 350,
    size: 'M',
    group: 'Women',
    category: 'Women',
    style: 'Traditional',
    type: 'Salwar Kameez',
    material: 'Cotton blend',
    usedFor: 'Used for 5 months',
    condition: 'Good',
    imageUrl: '/src/assets/products/salwar-kameez/olive-floral.jpg',
    image: '/src/assets/products/salwar-kameez/olive-floral.jpg',
  },

  // Men Traditional (Punjabis)
  {
    name: 'Royal Festive Punjabi',
    brand: 'Aarong',
    price: 800,
    size: 'L',
    group: 'Men',
    category: 'Men',
    style: 'Traditional',
    type: 'Punjabi',
    material: 'Silk blend',
    usedFor: 'Used for 1 month',
    condition: 'Like New',
    imageUrl: '/src/assets/products/punjabi-royal.jpg',
    image: '/src/assets/products/punjabi-royal.jpg',
  },
  {
    name: 'Lavender Printed Punjabi',
    brand: 'Aarong',
    price: 780,
    size: 'L',
    group: 'Men',
    category: 'Men',
    style: 'Traditional',
    type: 'Punjabi',
    material: 'Cotton blend',
    usedFor: 'Used for 1 month',
    condition: 'Like New',
    imageUrl: '/src/assets/products/punjabis/lavender-printed.jpg',
    image: '/src/assets/products/punjabis/lavender-printed.jpg',
  },
  {
    name: 'Sage Green Classic Punjabi',
    brand: 'Yellow',
    price: 520,
    size: 'M',
    group: 'Men',
    category: 'Men',
    style: 'Traditional',
    type: 'Punjabi',
    material: 'Soft cotton',
    usedFor: 'Used for 4 months',
    condition: 'Good',
    imageUrl: '/src/assets/products/punjabis/sage-classic.jpg',
    image: '/src/assets/products/punjabis/sage-classic.jpg',
  },
  {
    name: 'Navy Floral Punjabi',
    brand: 'Kay Kraft',
    price: 720,
    size: 'L',
    group: 'Men',
    category: 'Men',
    style: 'Traditional',
    type: 'Punjabi',
    material: 'Printed cotton',
    usedFor: 'Used for 2 months',
    condition: 'Like New',
    imageUrl: '/src/assets/products/punjabis/navy-floral.jpg',
    image: '/src/assets/products/punjabis/navy-floral.jpg',
  },
  {
    name: 'Mustard Motif Punjabi',
    brand: 'Aarong',
    price: 680,
    size: 'XL',
    group: 'Men',
    category: 'Men',
    style: 'Traditional',
    type: 'Punjabi',
    material: 'Cotton blend',
    usedFor: 'Used for 3 months',
    condition: 'Good',
    imageUrl: '/src/assets/products/punjabis/mustard-printed.jpg',
    image: '/src/assets/products/punjabis/mustard-printed.jpg',
  },

  // Men Western (Shirts, Suits, Jerseys)
  {
    name: 'Classic Men’s Suit',
    brand: 'Zara',
    price: 2400,
    size: 'L',
    group: 'Men',
    category: 'Men',
    style: 'Western',
    type: 'Suit',
    material: 'Wool blend',
    condition: 'Like New',
    imageUrl: '/src/assets/products/men-suit.jpg',
    image: '/src/assets/products/men-suit.jpg',
  },
  {
    name: 'White Linen Shirt',
    brand: 'H&M',
    price: 500,
    size: 'L',
    group: 'Men',
    category: 'Men',
    style: 'Western',
    type: 'Shirt',
    material: 'Pure linen',
    usedFor: 'Used for 1 month',
    condition: 'Like New',
    imageUrl: '/src/assets/products/shirts/white-linen.jpg',
    image: '/src/assets/products/shirts/white-linen.jpg',
  },
  {
    name: 'Oatmeal Linen Shirt',
    brand: 'Unbranded',
    price: 420,
    size: 'M',
    group: 'Men',
    category: 'Men',
    style: 'Western',
    type: 'Shirt',
    material: 'Linen blend',
    usedFor: 'Used for 3 months',
    condition: 'Good',
    imageUrl: '/src/assets/products/shirts/oatmeal-linen.jpg',
    image: '/src/assets/products/shirts/oatmeal-linen.jpg',
  },
  {
    name: 'Limited T-Shirt',
    brand: 'Nike',
    price: 180,
    size: 'M',
    group: 'Men',
    category: 'Men',
    style: 'Western',
    type: 'T-Shirt',
    material: 'Cotton jersey',
    usedFor: 'Used for 15 days',
    condition: 'Like New',
    imageUrl: '/src/assets/products/men-tshirt.jpg',
    image: '/src/assets/products/men-tshirt.jpg',
  },
  {
    name: 'Sports Jersey',
    brand: 'Adidas',
    price: 350,
    size: 'M',
    group: 'Men',
    category: 'Men',
    style: 'Western',
    type: 'Jersey',
    material: 'Polyester',
    usedFor: 'Used for 2 months',
    condition: 'Good',
    imageUrl:
      'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=1200&q=90',
    image:
      'https://images.unsplash.com/photo-1517466787929-bc90951d0974?auto=format&fit=crop&w=1200&q=90',
  },

  // Kids
  {
    name: 'Cherry Baby Bath Suit',
    brand: 'Mothercare',
    price: 320,
    size: '6–12 M',
    group: 'Kids',
    category: 'Kids',
    style: 'Western',
    type: 'Newborn',
    material: 'Soft cotton',
    usedFor: 'Used for 15 days',
    condition: 'Like New',
    imageUrl: '/src/assets/products/baby-bath-suit.jpg',
    image: '/src/assets/products/baby-bath-suit.jpg',
  },
  {
    name: 'Cotton Co-ord Set',
    brand: 'Yellow',
    price: 350,
    size: '1–2 Y',
    group: 'Kids',
    category: 'Kids',
    style: 'Western',
    type: '2–8 years',
    material: 'Pure cotton',
    usedFor: 'Used for 1 month',
    condition: 'Good',
    imageUrl: '/src/assets/products/cotton-co-ord-set.jpg',
    image: '/src/assets/products/cotton-co-ord-set.jpg',
    imageFit: 'contain',
  },
  {
    name: 'Smocked Puff Sleeve Dress',
    brand: 'Mothercare',
    price: 350,
    size: '1–2 Y',
    group: 'Kids',
    category: 'Kids',
    style: 'Western',
    type: '8–12 years',
    material: 'Cotton blend',
    usedFor: 'Used for 2 months',
    condition: 'Good',
    imageUrl: '/src/assets/products/smocked-baby-dress.jpg',
    image: '/src/assets/products/smocked-baby-dress.jpg',
    imageFit: 'contain',
  },
  {
    name: 'Newborn Baby Jumpsuit',
    brand: 'Baby Shop',
    price: 330,
    size: '0–6 M',
    group: 'Kids',
    category: 'Kids',
    style: 'Western',
    type: 'Newborn',
    material: 'Soft cotton',
    usedFor: 'Used for 1 month',
    condition: 'Like New',
    imageUrl: '/src/assets/products/newborn-baby-jumpsuit.jpg',
    image: '/src/assets/products/newborn-baby-jumpsuit.jpg',
  },
  {
    name: 'Floral Newborn Swimsuit',
    brand: 'Baby Shop',
    price: 300,
    size: '0–3 M',
    group: 'Kids',
    category: 'Kids',
    style: 'Western',
    type: 'Newborn',
    material: 'Cotton blend',
    usedFor: 'Used for 15 days',
    condition: 'Like New',
    imageUrl: '/src/assets/products/newborn/floral-swimsuit.jpg',
    image: '/src/assets/products/newborn/floral-swimsuit.jpg',
  },
  {
    name: 'Bear Print Baby Bodysuit',
    brand: 'Baby Shop',
    price: 350,
    size: '0–3 M',
    group: 'Kids',
    category: 'Kids',
    style: 'Western',
    type: 'Newborn',
    material: 'Pure cotton',
    usedFor: 'Used for 15 days',
    condition: 'Like New',
    imageUrl: '/src/assets/products/newborn/bear-bodysuit.jpg',
    image: '/src/assets/products/newborn/bear-bodysuit.jpg',
  },
];

async function seedDatabase() {
  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB.');

    console.log('Clearing existing products...');
    await Product.deleteMany({});

    console.log(`Inserting ${seedProductsData.length} products...`);
    const inserted = await Product.insertMany(seedProductsData);
    console.log(`Successfully seeded ${inserted.length} products into MongoDB!`);

    await mongoose.disconnect();
    console.log('Disconnected from MongoDB.');
    process.exit(0);
  } catch (error) {
    console.error('Seeding error:', error);
    process.exit(1);
  }
}

seedDatabase();
